### ISSUE TITLE
Formatter styles are applied to the <g> tag and not inherited

### ISSUE THREAD

**Issue by umesh-timalsina** [recogito/annotorious-openseadragon#47]
Thanks for this Plugin. I read through the documentation and tried to implement a custom style for the annotated rectangle. It looks like the style (returned as an object) or class (as a string) is applied to the parent svg `<g>` tag. But, its not actually inherited. I have attached below. Is this a bug? What's the correct way to apply formatter styles?

![image](https://user-images.githubusercontent.com/11476842/117103088-49584a80-ad3f-11eb-9deb-0d9768db4240.png)
![image](https://user-images.githubusercontent.com/11476842/117103168-7278db00-ad3f-11eb-9697-77d606bf849d.png)

**Comment by rsimon** [comment]
Hi,

ah, good point... hm, yes that's actually a leftover from a (very old) previous version. I need to rethink that part of the API, because the annotation now consists of two shape (inner and outer). The formatter API should probably have a way to apply styles to the shapes individually.

For a workaround: can you work with the string return type? That way you'd get the following markup:

```svg
<g class="a9s-annotation editable selected my-class-added-via-formatter" data-component="Inductor>
  <!-- ... -->
</g>
``` 

And you can use CSS rules in your stylesheet like so:

```css
.a9s-annotationlayer .a9s-annotation.my-class-added-via-formatter .a9s-outer {
  stroke-width:4;
  stroke:red;
}

.a9s-annotationlayer .a9s-annotation.my-class-added-via-formatter .a9s-inner {
  display:none;
}
```

Alternatively - in case all your Inductors share the same style - you can also apply CSS based on the data attribute:

```css
.a9s-annotationlayer .a9s-annotation[data-component="Inductor"] .a9s-outer {
  stroke-width:4;
  stroke:red;
}

.a9s-annotationlayer .a9s-annotation[data-component="Inductor"] .a9s-inner {
  display:none;
}
```
